In [ ]:
import numpy as pd

In [ ]:
li=[1,2,3,4,5]

In [ ]:
pd.array(li)

array([1, 2, 3, 4, 5])

In [ ]:
ml=[[1,2,3,],[4,5,6],[7,8,8]]

In [ ]:
pd.array(ml)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [ ]:
pd.zeros(3)

array([0., 0., 0.])

In [ ]:
pd.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
pd.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
pd.ones(3)

array([1., 1., 1.])

In [ ]:
pd.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
pd.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
pd.linspace(0,3,4)

array([0., 1., 2., 3.])

In [ ]:
pd.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [ ]:
pd.random.rand(10)

array([0.79280559, 0.33152964, 0.17327667, 0.81656545, 0.09533348,
       0.73084164, 0.58692387, 0.40017475, 0.93049759, 0.24032283])

In [ ]:
pd.random.rand((4))

array([0.81999071, 0.35679137, 0.83850997, 0.42550784])

In [ ]:
pd.random.randint(5)

3

In [ ]:
pd.random.randn(10)

array([ 1.06423654, -0.47478596, -0.20177583,  0.94378095, -1.43302476,
       -0.42609719, -0.60308128,  1.71331935, -0.13538965, -0.17777555])

In [ ]:
pd.random.randint(1,10)

6

In [ ]:
pd.random.randint(1,10,3)

array([1, 2, 1])

In [ ]:
pd.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.min()


0

In [ ]:
arr.max()

24

In [ ]:
arr.argmin()

0

In [ ]:
arr.argmax()

24

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5,5).shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr[0]

0

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[1:20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
arr1=arr.copy()

In [ ]:
arr.reshape(5,5)[2:4,1:5]

array([[11, 12, 13, 14],
       [16, 17, 18, 19]])

In [ ]:
arr[1:4]=20

In [ ]:
arr

array([ 0, 20, 20, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr>15

array([False,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [ ]:
arr.reshape(5,5)

array([[ 0, 20, 20, 20,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
boo=arr>15

In [ ]:
arr[boo]

array([20, 20, 20, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr1

array([ 0, 20, 20, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr=pd.arange(0,25)

In [ ]:
a1=pd.arange(0,10)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a1-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
a1/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
a1/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
a1*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import numpy as np


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
ar=np.arange(10,51)

In [ ]:
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
ar=np.arange(0,9)

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
ar.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.02036954])

In [ ]:
np.random.randn(25)

array([-0.7238162 , -1.31076552,  0.84081848,  1.86666771,  0.11521893,
       -0.21231141,  2.23467074,  0.74342039, -1.20327753, -0.77718573,
        1.24728207,  0.64176721,  0.11258575, -0.88809968,  1.20031024,
       -1.44148754,  0.31214453,  2.03835435,  0.05335087,  0.64909617,
       -0.35504392, -1.00266981,  0.2438277 , -0.53952981,  0.18970851])

In [ ]:
np.random.randn(5,5)

array([[-1.32645552,  1.03205083,  0.167961  ,  0.77040221, -0.38941076],
       [ 0.66233948,  0.80155433,  0.70675264,  0.15595491, -1.73112774],
       [-0.24648188, -0.8032466 , -0.25799377,  0.59947829,  0.19392076],
       [ 0.86048252, -0.16551393, -0.85685392, -1.31966489, -0.49814233],
       [-0.5556496 ,  2.43770001, -1.17022982,  0.96265875,  0.586215  ]])

In [ ]:
pd.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
ar=pd.arange(1,101)

In [ ]:
ar.reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
ar=np.arange(1,26).reshape(5,5)

In [ ]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ar[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
ar[3,4]

20

In [ ]:
ar[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
ar[4:]

array([[21, 22, 23, 24, 25]])

In [ ]:
ar[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ar.sum()

325

In [ ]:
ar.std()

7.211102550927978

In [ ]:
ar.